//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimuRails.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coche
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Coche()
        {
            this.Formacion_X_Coche = new HashSet<Formacion_X_Coche>();
        }
    
        public int Id { get; set; }
        public string Modelo { get; set; }
        public Nullable<bool> EsLocomotora { get; set; }
        public Nullable<int> TipoConsumo { get; set; }
        public Nullable<int> ConsumoMovimiento { get; set; }
        public Nullable<int> ConsumoParado { get; set; }
        public int CantidadAsientos { get; set; }
        public int MaximoLegalPasajeros { get; set; }
        public int CapacidadMaximaPasajeros { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Formacion_X_Coche> Formacion_X_Coche { get; set; }
    }
}
