//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ffccSimulacion.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coches
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Coches()
        {
            this.Formaciones_X_Coches = new HashSet<Formaciones_X_Coches>();
        }
    
        public int Id { get; set; }
        public string Modelo { get; set; }
        public Nullable<int> EsLocomotora { get; set; }
        public Nullable<int> TipoConsumo { get; set; }
        public Nullable<int> ConsumoMovimiento { get; set; }
        public Nullable<int> ConsumoParado { get; set; }
        public int CantidadAsientos { get; set; }
        public int MaximoLegalPasajeros { get; set; }
        public int CapacidadMaximaPasajeros { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Formaciones_X_Coches> Formaciones_X_Coches { get; set; }
    }
}
