//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimuRails.Model.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SimuRailsEntities : DbContext
    {
        public SimuRailsEntities()
            : base("name=SimuRailsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Coche> Coche { get; set; }
        public virtual DbSet<Estacion> Estacion { get; set; }
        public virtual DbSet<Estacion_X_Incidente> Estacion_X_Incidente { get; set; }
        public virtual DbSet<Formacion> Formacion { get; set; }
        public virtual DbSet<Formacion_X_Coche> Formacion_X_Coche { get; set; }
        public virtual DbSet<Incidente> Incidente { get; set; }
        public virtual DbSet<Servicio> Servicio { get; set; }
        public virtual DbSet<Servicio_X_Formacion> Servicio_X_Formacion { get; set; }
        public virtual DbSet<Simulacion> Simulacion { get; set; }
        public virtual DbSet<Tramo> Tramo { get; set; }
        public virtual DbSet<Traza> Traza { get; set; }
        public virtual DbSet<Traza_X_Servicio> Traza_X_Servicio { get; set; }
    }
}
