//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ffccSimulacion.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Estaciones()
        {
            this.Estaciones_X_Incidentes = new HashSet<Estaciones_X_Incidentes>();
            this.Relaciones = new HashSet<Relaciones>();
            this.Relaciones1 = new HashSet<Relaciones>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public int PersonasEsperandoMin { get; set; }
        public int PersonasEsperandoMax { get; set; }
        public int TipoFDP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estaciones_X_Incidentes> Estaciones_X_Incidentes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Relaciones> Relaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Relaciones> Relaciones1 { get; set; }
    }
}
