//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ffccSimulacion.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estaciones_X_Incidentes
    {
        public int Id { get; set; }
        public int Id_Incidente { get; set; }
        public int Id_Estacion { get; set; }
    
        public virtual Estaciones Estaciones { get; set; }
        public virtual Incidentes Incidentes { get; set; }
    }
}
