//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ffccSimulacion.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Formaciones_X_Coches
    {
        public int Id { get; set; }
        public int Id_Formacion { get; set; }
        public int Id_Coche { get; set; }
        public int VecesRepetido { get; set; }
    
        public virtual Coches Coches { get; set; }
        public virtual Formaciones Formaciones { get; set; }
    }
}
