//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ffccSimulacion.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relaciones
    {
        public int Id { get; set; }
        public int Id_Estacion_Anterior { get; set; }
        public int Id_Estacion_Siguiente { get; set; }
        public int Id_Servicio { get; set; }
        public int Distancia { get; set; }
        public int TiempoViaje { get; set; }
        public int Est_Sig_Es_Parada { get; set; }
    
        public virtual Estaciones Estaciones { get; set; }
        public virtual Estaciones Estaciones1 { get; set; }
        public virtual Servicios Servicios { get; set; }
    }
}
