//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimuRails.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicio_X_Formacion
    {
        public int Id { get; set; }
        public int Id_Servicio { get; set; }
        public int Id_Formacion { get; set; }
        public Nullable<int> CantFormaciones { get; set; }
    
        public virtual Formacion Formacion { get; set; }
        public virtual Servicio Servicio { get; set; }
    }
}
