//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ffccSimulacion.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Simulaciones
    {
        public int Id { get; set; }
        public int Tiempo_Inicial { get; set; }
        public int Tiempo_Final { get; set; }
        public int Id_Traza { get; set; }
        public string Nombre { get; set; }
    
        public virtual Trazas Trazas { get; set; }
    }
}
