//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimuRails.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estacion_X_Incidente
    {
        public int Id { get; set; }
        public int Id_Incidente { get; set; }
        public int Id_Estacion { get; set; }
    
        public virtual Estacion Estacion { get; set; }
        public virtual Incidente Incidente { get; set; }
    }
}
