//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimuRails.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Simulacion
    {
        public int Id { get; set; }
        public int TiempoInicial { get; set; }
        public int TiempoFinal { get; set; }
        public int Id_Traza { get; set; }
        public string Nombre { get; set; }
    
        public virtual Traza Traza { get; set; }
    }
}
